# Generated by Django 6.0.7 on 2026-07-14 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("priority", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={
                "ordering": ("name",),
                "verbose_name": "task type",
                "verbose_name_plural": "task types",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("TECH_REVIEW", "Tech Review"),
                    ("QA", "QA"),
                    ("REWORK", "Rework"),
                    ("MERGED", "Merged"),
                    ("DEPLOYMENT", "Deployment"),
                    ("DONE", "Done"),
                    ("BACKLOG", "Backlog"),
                ],
                default="TO_DO",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.tasktype",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Urgent"), (2, "High"), (3, "Medium"), (4, "Low")],
                default=3,
            ),
        ),
    ]
