# Generated by Django 6.0.7 on 2026-07-17 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_options_alter_tasktype_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_like_comment_user",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
